#!/bin/zsh
git checkout gh-pages
mkdir /optemo/optemocom_flat
cd /optemo/optemocom_flat
rm -rf /optemo/optemocom_flat/*
wget -r --adjust-extension http://localhost:3000/
mv localhost:3000/* .
rm -rf localhost:3000
autoload zmv

find /optemo/optemocom -type f|grep -v ".git\|CNAME"|xargs rm -rf
cp -r /optemo/optemocom_flat/* /optemo/optemocom/
